/**
 * Bootstrap footballer rows for FootballPlayer.
 * Kept separate from runtime loaders so admin + migrate seed share one list.
 */

import type { MysteryPlayer } from "./types";

/** Default catalog seeded into DB when empty / on ensure. */
export const SEED_FOOTBALL_PLAYERS: MysteryPlayer[] = [
  {
    id: "messi",
    nameEn: "Lionel Messi",
    nameFa: "لیونل مسی",
    nationality: "Argentina",
    nationalityCode: "AR",
    position: "FWD",
    league: "MLS",
    club: "Inter Miami",
    age: 37,
    shirtNumber: 10,
  },
  {
    id: "ronaldo",
    nameEn: "Cristiano Ronaldo",
    nameFa: "کریستیانو رونالدو",
    nationality: "Portugal",
    nationalityCode: "PT",
    position: "FWD",
    league: "Saudi Pro League",
    club: "Al Nassr",
    age: 40,
    shirtNumber: 7,
  },
  {
    id: "mbappe",
    nameEn: "Kylian Mbappé",
    nameFa: "کیلیان امباپه",
    nationality: "France",
    nationalityCode: "FR",
    position: "FWD",
    league: "La Liga",
    club: "Real Madrid",
    age: 26,
    shirtNumber: 9,
  },
  {
    id: "haaland",
    nameEn: "Erling Haaland",
    nameFa: "ارلینگ هالند",
    nationality: "Norway",
    nationalityCode: "NO",
    position: "FWD",
    league: "Premier League",
    club: "Manchester City",
    age: 24,
    shirtNumber: 9,
  },
  {
    id: "salah",
    nameEn: "Mohamed Salah",
    nameFa: "محمد صلاح",
    nationality: "Egypt",
    nationalityCode: "EG",
    position: "FWD",
    league: "Premier League",
    club: "Liverpool",
    age: 32,
    shirtNumber: 11,
  },
  {
    id: "de_bruyne",
    nameEn: "Kevin De Bruyne",
    nameFa: "کوین دی‌بروینه",
    nationality: "Belgium",
    nationalityCode: "BE",
    position: "MID",
    league: "Premier League",
    club: "Manchester City",
    age: 33,
    shirtNumber: 17,
  },
  {
    id: "modric",
    nameEn: "Luka Modrić",
    nameFa: "لوکا مودریچ",
    nationality: "Croatia",
    nationalityCode: "HR",
    position: "MID",
    league: "Saudi Pro League",
    club: "Al Nassr",
    age: 39,
    shirtNumber: 10,
  },
  {
    id: "bellingham",
    nameEn: "Jude Bellingham",
    nameFa: "جود بلینگام",
    nationality: "England",
    nationalityCode: "GB",
    position: "MID",
    league: "La Liga",
    club: "Real Madrid",
    age: 21,
    shirtNumber: 5,
  },
  {
    id: "vinicius",
    nameEn: "Vinícius Júnior",
    nameFa: "وینیسیوس جونیور",
    nationality: "Brazil",
    nationalityCode: "BR",
    position: "FWD",
    league: "La Liga",
    club: "Real Madrid",
    age: 24,
    shirtNumber: 7,
  },
  {
    id: "neymar",
    nameEn: "Neymar",
    nameFa: "نیمار",
    nationality: "Brazil",
    nationalityCode: "BR",
    position: "FWD",
    league: "Saudi Pro League",
    club: "Al Hilal",
    age: 33,
    shirtNumber: 10,
  },
  {
    id: "van_dijk",
    nameEn: "Virgil van Dijk",
    nameFa: "ویرجیل فن‌دایک",
    nationality: "Netherlands",
    nationalityCode: "NL",
    position: "DEF",
    league: "Premier League",
    club: "Liverpool",
    age: 33,
    shirtNumber: 4,
  },
  {
    id: "alisson",
    nameEn: "Alisson",
    nameFa: "آلیسون",
    nationality: "Brazil",
    nationalityCode: "BR",
    position: "GK",
    league: "Premier League",
    club: "Liverpool",
    age: 32,
    shirtNumber: 1,
  },
  {
    id: "courtois",
    nameEn: "Thibaut Courtois",
    nameFa: "تیبو کورتوا",
    nationality: "Belgium",
    nationalityCode: "BE",
    position: "GK",
    league: "La Liga",
    club: "Real Madrid",
    age: 33,
    shirtNumber: 1,
  },
  {
    id: "taremi",
    nameEn: "Mehdi Taremi",
    nameFa: "مهدی طارمی",
    nationality: "Iran",
    nationalityCode: "IR",
    position: "FWD",
    league: "Serie A",
    club: "Inter",
    age: 32,
    shirtNumber: 99,
  },
  {
    id: "jahanbakhsh",
    nameEn: "Alireza Jahanbakhsh",
    nameFa: "علیرضا جهانبخش",
    nationality: "Iran",
    nationalityCode: "IR",
    position: "FWD",
    league: "Eredivisie",
    club: "Heerenveen",
    age: 31,
    shirtNumber: 7,
  },
  {
    id: "ghoddos",
    nameEn: "Saman Ghoddos",
    nameFa: "سامان قدوس",
    nationality: "Iran",
    nationalityCode: "IR",
    position: "MID",
    league: "Championship",
    club: "Charlton Athletic",
    age: 31,
    shirtNumber: 14,
  },
  {
    id: "lewandowski",
    nameEn: "Robert Lewandowski",
    nameFa: "روبرت لواندوفسکی",
    nationality: "Poland",
    nationalityCode: "PL",
    position: "FWD",
    league: "La Liga",
    club: "Barcelona",
    age: 36,
    shirtNumber: 9,
  },
  {
    id: "kane",
    nameEn: "Harry Kane",
    nameFa: "هری کین",
    nationality: "England",
    nationalityCode: "GB",
    position: "FWD",
    league: "Bundesliga",
    club: "Bayern Munich",
    age: 31,
    shirtNumber: 9,
  },
  {
    id: "rodri",
    nameEn: "Rodri",
    nameFa: "رودری",
    nationality: "Spain",
    nationalityCode: "ES",
    position: "MID",
    league: "Premier League",
    club: "Manchester City",
    age: 28,
    shirtNumber: 16,
  },
  {
    id: "yamal",
    nameEn: "Lamine Yamal",
    nameFa: "لامین یامال",
    nationality: "Spain",
    nationalityCode: "ES",
    position: "FWD",
    league: "La Liga",
    club: "Barcelona",
    age: 17,
    shirtNumber: 19,
  },
];

/** Deterministic pick among a slug list (stable across servers). */
export function pickSlugForDateKey(dateKey: string, slugs: string[]): string {
  if (slugs.length === 0) {
    throw new Error("no_active_players");
  }
  let hash = 0;
  for (let i = 0; i < dateKey.length; i++) {
    hash = (hash * 31 + dateKey.charCodeAt(i)) >>> 0;
  }
  return slugs[hash % slugs.length]!;
}
